"""Discrete-logarithm algorithms with inspectable classroom traces.

The algorithms here work in the multiplicative group modulo a prime (or in a
known cyclic subgroup of a unit group).  They deliberately favour clear state
over the optimisations and side-channel protections needed in production.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from math import gcd, isqrt
from random import Random

from ecc_factor import factor_counts, is_probable_prime

from .algebra import chinese_remainder_theorem, multiplicative_order
from .number_theory import mod_inverse
from .trace import TraceCallback, emit


class DiscreteLogError(RuntimeError):
    """Raised when a bounded discrete-logarithm search cannot continue."""


def _validate_group(base: int, target: int, modulus: int, order: int | None) -> tuple[int, int, int, int]:
    for value, name in ((base, "base"), (target, "target"), (modulus, "modulus")):
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError(f"{name} must be an integer")
    if modulus < 2:
        raise ValueError("modulus must be at least 2")
    base %= modulus
    target %= modulus
    if gcd(base, modulus) != 1:
        raise ValueError("base must be invertible modulo modulus")
    if gcd(target, modulus) != 1:
        raise ValueError("target must be invertible modulo modulus")
    if order is None:
        order = multiplicative_order(base, modulus)
    if order < 1 or pow(base, order, modulus) != 1:
        raise ValueError("order must be a positive multiple of the base order")
    return base, target, modulus, order


def baby_step_giant_step(
    base: int,
    target: int,
    modulus: int,
    *,
    order: int | None = None,
    trace: TraceCallback | None = None,
) -> int | None:
    """Solve ``base**x == target (mod modulus)`` with BSGS.

    The returned exponent is the least non-negative solution modulo the
    supplied subgroup order, or ``None`` when the target is outside the
    subgroup generated by ``base``.
    """

    base, target, modulus, order = _validate_group(base, target, modulus, order)
    if pow(target, order, modulus) != 1:
        emit(trace, "dlog.outside_subgroup", "target is outside the base subgroup", target=target, order=order)
        return None

    step = isqrt(order - 1) + 1
    baby: dict[int, int] = {}
    value = 1
    for j in range(step):
        baby.setdefault(value, j)
        emit(trace, "bsgs.baby", f"baby step j={j}: {value}", level=2, index=j, value=value)
        value = value * base % modulus

    factor = pow(mod_inverse(base, modulus), step, modulus)
    gamma = target
    for i in range(step + 1):
        j = baby.get(gamma)
        emit(
            trace,
            "bsgs.giant",
            f"giant step i={i}: {gamma}{' matches' if j is not None else ''}",
            level=2,
            index=i,
            value=gamma,
            baby_index=j,
        )
        if j is not None:
            candidate = i * step + j
            if candidate < order and pow(base, candidate, modulus) == target:
                emit(
                    trace,
                    "bsgs.complete",
                    f"discrete log found: {candidate}",
                    base=base,
                    target=target,
                    modulus=modulus,
                    order=order,
                    result=candidate,
                )
                return candidate
        gamma = gamma * factor % modulus
    emit(trace, "bsgs.not_found", "no discrete logarithm in the requested subgroup", order=order)
    return None


def _prime_power_digits(
    base: int,
    target: int,
    modulus: int,
    prime: int,
    exponent: int,
    subgroup_order: int,
    *,
    trace: TraceCallback | None = None,
) -> int | None:
    """Solve one ``q**e`` component in Pohlig--Hellman."""

    cofactor = subgroup_order // (prime**exponent)
    component_base = pow(base, cofactor, modulus)
    component_target = pow(target, cofactor, modulus)
    component = 0
    # Every digit is compared in the same order-q subgroup generated by
    # ``component_base ** (q ** (e - 1))``.  The exponent applied to the
    # adjusted target changes with the digit position; the base does not.
    digit_base = pow(component_base, prime ** (exponent - 1), modulus)
    emit(
        trace,
        "pohlig_hellman.component",
        f"solve subgroup of order {prime}^{exponent}",
        prime=prime,
        exponent=exponent,
        cofactor=cofactor,
        base=component_base,
        target=component_target,
    )

    for digit_index in range(exponent):
        remaining_power = prime ** (exponent - digit_index - 1)
        adjusted = component_target * pow(
            mod_inverse(component_base, modulus), component, modulus
        ) % modulus
        digit_target = pow(adjusted, remaining_power, modulus)
        digit: int | None = None
        for candidate in range(prime):
            if pow(digit_base, candidate, modulus) == digit_target:
                digit = candidate
                break
        if digit is None:
            emit(
                trace,
                "pohlig_hellman.digit_failure",
                f"no base-{prime} digit at position {digit_index}",
                prime=prime,
                digit_index=digit_index,
            )
            return None
        component += digit * (prime**digit_index)
        emit(
            trace,
            "pohlig_hellman.digit",
            f"digit {digit_index} = {digit}; component = {component}",
            level=2,
            prime=prime,
            digit_index=digit_index,
            digit=digit,
            component=component,
        )
    return component


def pohlig_hellman(
    base: int,
    target: int,
    modulus: int,
    *,
    order: int | None = None,
    order_factors: Mapping[int, int] | Iterable[int] | None = None,
    trace: TraceCallback | None = None,
) -> int | None:
    """Solve a discrete logarithm when the subgroup order is smooth.

    ``modulus`` is expected to be prime for the standard Pohlig--Hellman
    setting.  The optional ``order`` and ``order_factors`` make the subgroup
    explicit, which is useful when demonstrating a small subgroup.
    """

    base, target, modulus, order = _validate_group(base, target, modulus, order)
    if not is_probable_prime(modulus):
        raise ValueError("Pohlig-Hellman teaching implementation requires a prime modulus")
    if pow(target, order, modulus) != 1:
        return None
    counts = _normalise_factors(order, order_factors)
    residues: list[tuple[int, int]] = []
    for prime, exponent in sorted(counts.items()):
        modulus_part = prime**exponent
        component = _prime_power_digits(
            base,
            target,
            modulus,
            prime,
            exponent,
            order,
            trace=trace,
        )
        if component is None:
            return None
        residues.append((component, modulus_part))

    result, combined_order = chinese_remainder_theorem(residues, trace=trace)
    if combined_order != order:
        raise DiscreteLogError("order factorization did not reconstruct the subgroup order")
    if pow(base, result, modulus) != target:
        emit(trace, "pohlig_hellman.not_found", "component logs did not verify", candidate=result)
        return None
    emit(
        trace,
        "pohlig_hellman.complete",
        f"discrete log found: {result}",
        base=base,
        target=target,
        modulus=modulus,
        order=order,
        result=result,
    )
    return result


def _normalise_factors(
    number: int,
    factors: Mapping[int, int] | Iterable[int] | None,
) -> dict[int, int]:
    if factors is None:
        return factor_counts(number)
    if isinstance(factors, Mapping):
        counts = dict(factors)
    else:
        counts: dict[int, int] = {}
        for prime in factors:
            counts[prime] = counts.get(prime, 0) + 1
    product = 1
    for prime, exponent in counts.items():
        if prime < 2 or exponent < 1:
            raise ValueError("order factors must be positive prime powers")
        product *= prime**exponent
    if product != number:
        raise ValueError("order_factors do not multiply to order")
    return counts


def _solve_linear_congruence(coefficient: int, constant: int, modulus: int) -> list[int]:
    """Return solutions of ``coefficient*x == constant (mod modulus)``."""

    divisor = gcd(coefficient, modulus)
    if constant % divisor:
        return []
    reduced_modulus = modulus // divisor
    if reduced_modulus == 1:
        return list(range(modulus))
    reduced_coefficient = coefficient // divisor % reduced_modulus
    reduced_constant = constant // divisor % reduced_modulus
    first = reduced_constant * mod_inverse(reduced_coefficient, reduced_modulus) % reduced_modulus
    return [first + index * reduced_modulus for index in range(divisor)]


def pollard_rho_discrete_log(
    base: int,
    target: int,
    modulus: int,
    *,
    order: int | None = None,
    seed: int | None = None,
    attempts: int = 16,
    max_steps: int | None = None,
    trace: TraceCallback | None = None,
) -> int | None:
    """Solve a discrete logarithm with Pollard's rho random-walk method.

    A restart is used when a collision produces a non-invertible congruence;
    this is common when the subgroup order is composite and is useful to show
    students why a prime-order subgroup is preferred in practice.
    """

    base, target, modulus, order = _validate_group(base, target, modulus, order)
    if attempts < 1:
        raise ValueError("attempts must be positive")
    if max_steps is None:
        max_steps = max(32, 8 * isqrt(order) + 16)
    if max_steps < 1:
        raise ValueError("max_steps must be positive")
    if pow(target, order, modulus) != 1:
        return None
    rng = Random(seed)

    def walk(state: tuple[int, int, int]) -> tuple[int, int, int]:
        value, exponent_base, exponent_target = state
        bucket = value % 3
        if bucket == 0:
            value = value * base % modulus
            exponent_base = (exponent_base + 1) % order
        elif bucket == 1:
            value = value * target % modulus
            exponent_target = (exponent_target + 1) % order
        else:
            value = value * value % modulus
            exponent_base = (2 * exponent_base) % order
            exponent_target = (2 * exponent_target) % order
        return value, exponent_base, exponent_target

    for attempt in range(1, attempts + 1):
        initial = rng.randrange(order)
        state = (pow(base, initial, modulus), initial, 0)
        tortoise = walk(state)
        hare = walk(walk(state))
        emit(
            trace,
            "rho_dlog.attempt",
            f"Pollard-rho DLP attempt {attempt}",
            attempt=attempt,
            initial=initial,
        )
        for step in range(1, max_steps + 1):
            if tortoise[0] == hare[0]:
                # g^(a_t-a_h) = h^(b_h-b_t), hence
                # (b_h-b_t)*x = a_t-a_h (mod order).
                coefficient = (hare[2] - tortoise[2]) % order
                constant = (tortoise[1] - hare[1]) % order
                candidates = _solve_linear_congruence(coefficient, constant, order)
                emit(
                    trace,
                    "rho_dlog.collision",
                    f"collision at step {step}; {coefficient}x = {constant} (mod {order})",
                    level=2,
                    attempt=attempt,
                    step=step,
                    coefficient=coefficient,
                    constant=constant,
                    candidates=tuple(candidates),
                )
                for candidate in candidates:
                    candidate %= order
                    if pow(base, candidate, modulus) == target:
                        emit(
                            trace,
                            "rho_dlog.complete",
                            f"discrete log found: {candidate}",
                            attempt=attempt,
                            step=step,
                            result=candidate,
                        )
                        return candidate
                break
            tortoise = walk(tortoise)
            hare = walk(walk(hare))
            if step <= 8 or step % max(1, max_steps // 8) == 0:
                emit(trace, "rho_dlog.step", f"rho step {step}", level=2, step=step, attempt=attempt)
        emit(trace, "rho_dlog.restart", f"restart after attempt {attempt}", attempt=attempt)
    emit(trace, "rho_dlog.not_found", "Pollard-rho DLP search exhausted its budget", attempts=attempts)
    return None


# Names commonly used in lecture notes and problem sets.
discrete_log_bsgs = baby_step_giant_step
discrete_log_pohlig_hellman = pohlig_hellman
pollard_rho_dlog = pollard_rho_discrete_log
bsgs = baby_step_giant_step
pollard_rho = pollard_rho_discrete_log


__all__ = [
    "DiscreteLogError",
    "baby_step_giant_step",
    "bsgs",
    "discrete_log_bsgs",
    "discrete_log_pohlig_hellman",
    "pohlig_hellman",
    "pollard_rho_discrete_log",
    "pollard_rho_dlog",
    "pollard_rho",
]
